### ISSUE TITLE
Erratic Data on Arduino

### ISSUE THREAD

**Issue by Koryori** [yanghu/FlightPanel#1]
Hello!  Thanks for the great work.  I am on a learning curve on this but wondered if you could guide me a bit with my problem.

Your codes works just fine until I begin to add more flight parameters such as air speed, VS, etc. to experience data received are no longer correct but very strange numbers.  Even those parameters if I limit upto 3, things work great.  I suspect data buffer issue happening?  But not sure.

To test the communication I attach a 20x4 character display driven by Arduino Nano, and nothing else.

**Comment by yanghu** [comment]
The data types are not really portable between Arduino and PC, which means the bytes will be interpreted incorrectly. 
For example, "double" is 4 bytes on Arduino, and 8 bytes on PC.
It's fragile to directly use the buffer of struct to transfer data. That's why I converted values to char before sending them to Arduino for simplicity.
For my use case it was simple enough to just use `char`. If I'd add more data to transmit to the board, I'd probably use protobuf (NanoPB lib works for Arduino) to serialize the data.
You can also encode the data in your own way, or use some libraries can do that (also maybe add framing to the data).

**Comment by Koryori** [comment]
Thank you so much for your help!!  Yes, I changed every parameter format to char, and now I get what I want (speed, heading, alt, RPM, VS, Gear pos, flap index, bank, pitch, and parking brake) on the LCD display.  I had to make my dirty codes to separate an integer into a few char value to send to Arduino, etc. but the rest of your program just worked fine. 

So happy to see it's working!  Thank you very much again.
